/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.3.144 */
/* Module Version: 5.7 */
/* Sun Feb 03 19:55:48 2019 */

/* parameterized module instance */
my_pll_64mhz __ (.CLKI( ), .CLKI2( ), .SEL( ), .CLKOP( ), .LOCK( ));
